### PR TITLE
Add link to Czech localization

### PR DESCRIPTION
**Pull request by mormegil-cz**
I have created the Czech translation of bobby-tables.com and published it at http://bobby-tables.cz/

It would be great if you could add a link to the translation into the footer at bobby-tables.com.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the translation, but I've had to remove the translations from the site.  You're more than welcome to translate the site and host it on a website of your own.  If you do, please let me know and I'll list it on the site.

**Comment by mormegil-cz** [comment]
OK, maybe I don’t understand, but this is exactly what I have done and what I have requested. I.e. I had translated the site and I have been hosting it on my own website, http://bobby-tables.cz/ and I asked only to list the translation on the main site.

**Comment by petdance** [comment]
I'm sorry, I misread your note.  My mistake.  I will link to your site.

Note that the translations for `Čeština / Deutsch / Русский язык / Español / English` at the bottom of bobby-tables.cz are no longer valid.  They've all been deleted.

**Comment by petdance** [comment]
Thanks for this.  I've added it to the front page.

**Pull request closed without merging**
