### PR TITLE
Creates ADO.NET page and ADO.NET ORM page

### LINKED ISSUE #79: Consolidate C#, .NET, and ASP pages into single .NET page (with or without subpages)
The information for avoiding SQL injection in .NET is currently fragmented over 3 different pages: [C#](http://bobby-tables.com/csharp), [.NET](http://bobby-tables.com/dotnet), and [ASP](http://bobby-tables.com/asp). It should really be consolidated into a single page (with or without subpages as appropriate), and should be structured as follows:

* Direct ADO.NET
  - Using the base classes in [**System.Data.Common**](https://docs.microsoft.com/en-us/dotnet/api/system.data.common?view=netframework-4.7.2)
  - [Built-in providers](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers)
    - [SQL Server](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-includessnoversionincludesssnoversion-mdmd-sqlclient)
    - [OLE DB](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-ole-db)
    - [ODBC](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-odbc)
  - Third-party providers
    - [Oracle](http://www.oracle.com/technetwork/topics/dotnet/index-085163.html)
    - Postgresql
    - [MySQL](https://dev.mysql.com/downloads/connector/net/6.10.html)
    - [SQLite](https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki)
* Entity Framework Core ?
* EF 6
  - [ExecuteSQLCommand](https://msdn.microsoft.com/en-us/library/system.data.entity.database.executesqlcommand(v=vs.113).aspx) and [ExecuteSQLCommandSync](https://msdn.microsoft.com/en-us/library/system.data.entity.database.executesqlcommandasync(v=vs.113).aspx) methods
  - [SqlQuery](https://msdn.microsoft.com/en-us/library/system.data.entity.database.sqlquery(v=vs.113).aspx) method
* Dapper
* Additional ORMs

This information is the same for any .NET language -- C#, VB.NET, F#, IronPython -- and for every .NET programming environment -- ASP.NET, WPF, console application, WinForms. At best it might be good to have examples for various languages on each subsection.

One important note: some providers support named parameters (e.g. the SQL Server provider); some providers support position parameters (e.g. the OLE DB provider).

### PR DESCRIPTION
**Pull request by zspitz**
Fixes #79

This page now supersedes the previous C# and .NET pages, and part of the ASP page.

@mason-mcglothlin @kimmel @deanebarker As previous contributors to these pages, could you look over this and see if I've missed anything?

Question: do we also need an example for preventing SQL injection when syncing edited data from a dataset back to the data source? Is this a reasonable scenario? (I've never used a dataset in this way.)

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this.  Will try to look at it this weekend.

**Comment by petdance** [comment]
Can you say more please about how this update supersedes the other pages?  How exactly?  I don't know anything about this ecosystem.

**Comment by mason-mcglothlin** [comment]
@petdance 

Data access in any .NET application is done in the same way. C# is just a language in .NET. So it didn't make sense to have .NET and C# split onto different pages. ASP.NET is a web application framework that's part of .NET, so that didn't make sense to separate out either. We can combine all of these and then we won't have to maintain separate examples.

I will look into the changes when I have a bit more time to go over them, hopefully this evening.

**Comment by petdance** [comment]
So you're combining two related pages into one?  That makes sense, thank you.  My concern was that we might be losing information about older languages that still might be being used.

**Comment by petdance** [comment]
It seems like you're still working on this PR, correct?  Can you please delete the PR and then make a new one when you're ready for me to merge it?

**Comment by zspitz** [comment]
@petdance These are minor corrections, typos etc. I'll hold off for now.

**Comment by petdance** [comment]
This has been closed and reopened as #86

**Pull request closed without merging**
